firstName = str(input('Enter your first name: '))
lastName = str(input('Enter your last name: '))
age = int(input('Enter your age: '))
ssn = int(input('Enter your ssn number: '))
height = float(input('Enter your height: '))
weight = float(input('Enter your weight: '))

print('firstName: ', firstName)
print(type(firstName))
print('lastName: ', lastName)
print(type(lastName))
print('age: ', age)
print(type(age))
print('ssn: ', ssn)
print(type(ssn))
print('height: ', height)
print(type(height))
print('weight: ', weight)
print(type(weight))